DirCreate("E:\ToolBox\软件工具箱\dhxtool\config")
FileInstall("E:\ToolBox\软件工具箱\config\config\form.ini", "E:\ToolBox\软件工具箱\dhxtool\config\form.ini", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Edge.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\Edge.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\EXCEL.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\EXCEL.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Explorer.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\Explorer.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\PPT.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\PPT.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\QQ.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\QQ.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\regedit.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\regedit.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\ruanjian.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\ruanjian.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\shezhi.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\shezhi.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\sousuo.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\sousuo.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Taskmgr.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\Taskmgr.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\VX.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\VX.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\WinTools.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\WinTools.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Word.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\Word.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\zhankai.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\zhankai.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\zhedie.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\Form\zhedie.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\办公设计")
FileInstall("E:\ToolBox\软件工具箱\config\icon\办公设计\ABBYY_FineReader.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\办公设计\ABBYY_FineReader.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\在线安装")
FileInstall("E:\ToolBox\软件工具箱\config\icon\在线安装\LKY_OfficeTools.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\在线安装\LKY_OfficeTools.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\icon\常用网站")
FileInstall("E:\ToolBox\软件工具箱\config\icon\常用网站\Chrome.ico", "E:\ToolBox\软件工具箱\dhxtool\icon\常用网站\Chrome.ico", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\skin")
FileInstall("E:\ToolBox\软件工具箱\config\skin\water.dll", "E:\ToolBox\软件工具箱\dhxtool\skin\water.dll", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\主窗口背景.jpg", "E:\ToolBox\软件工具箱\dhxtool\skin\主窗口背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\提示背景.jpg", "E:\ToolBox\软件工具箱\dhxtool\skin\提示背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\欢迎背景.jpg", "E:\ToolBox\软件工具箱\dhxtool\skin\欢迎背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\水纹.bmp", "E:\ToolBox\软件工具箱\dhxtool\skin\水纹.bmp", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\软件大窗口背景.jpg", "E:\ToolBox\软件工具箱\dhxtool\skin\软件大窗口背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\软件窗口背景.jpg", "E:\ToolBox\软件工具箱\dhxtool\skin\软件窗口背景.jpg", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\tools")
FileInstall("E:\ToolBox\软件工具箱\config\tools\7z.dll", "E:\ToolBox\软件工具箱\dhxtool\tools\7z.dll", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\7z.exe", "E:\ToolBox\软件工具箱\dhxtool\tools\7z.exe", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\aria2c.exe", "E:\ToolBox\软件工具箱\dhxtool\tools\aria2c.exe", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\Canon.ani", "E:\ToolBox\软件工具箱\dhxtool\tools\Canon.ani", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\ChkMbrPbr_x64.exe", "E:\ToolBox\软件工具箱\dhxtool\tools\ChkMbrPbr_x64.exe", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\ChkMbrPbr_x86.exe", "E:\ToolBox\软件工具箱\dhxtool\tools\ChkMbrPbr_x86.exe", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\curl-ca-bundle.crt", "E:\ToolBox\软件工具箱\dhxtool\tools\curl\curl-ca-bundle.crt", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\curl.exe", "E:\ToolBox\软件工具箱\dhxtool\tools\curl\curl.exe", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\libcurl.def", "E:\ToolBox\软件工具箱\dhxtool\tools\curl\libcurl.def", 0)
DirCreate("E:\ToolBox\软件工具箱\dhxtool\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\libcurl.dll", "E:\ToolBox\软件工具箱\dhxtool\tools\curl\libcurl.dll", 0)
