DirCreate( @ScriptDir &'\dhxtool' & "\config")
FileInstall("E:\ToolBox\软件工具箱\config\config\form.ini", @ScriptDir &'\dhxtool' & "\config\form.ini", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Edge.ico", @ScriptDir &'\dhxtool' & "\icon\Form\Edge.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\EXCEL.ico", @ScriptDir &'\dhxtool' & "\icon\Form\EXCEL.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Explorer.ico", @ScriptDir &'\dhxtool' & "\icon\Form\Explorer.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\PPT.ico", @ScriptDir &'\dhxtool' & "\icon\Form\PPT.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\QQ.ico", @ScriptDir &'\dhxtool' & "\icon\Form\QQ.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\regedit.ico", @ScriptDir &'\dhxtool' & "\icon\Form\regedit.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\ruanjian.ico", @ScriptDir &'\dhxtool' & "\icon\Form\ruanjian.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\shezhi.ico", @ScriptDir &'\dhxtool' & "\icon\Form\shezhi.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\sousuo.ico", @ScriptDir &'\dhxtool' & "\icon\Form\sousuo.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Taskmgr.ico", @ScriptDir &'\dhxtool' & "\icon\Form\Taskmgr.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\VX.ico", @ScriptDir &'\dhxtool' & "\icon\Form\VX.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\WinTools.ico", @ScriptDir &'\dhxtool' & "\icon\Form\WinTools.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\Word.ico", @ScriptDir &'\dhxtool' & "\icon\Form\Word.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\zhankai.ico", @ScriptDir &'\dhxtool' & "\icon\Form\zhankai.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\Form")
FileInstall("E:\ToolBox\软件工具箱\config\icon\Form\zhedie.ico", @ScriptDir &'\dhxtool' & "\icon\Form\zhedie.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\办公设计")
FileInstall("E:\ToolBox\软件工具箱\config\icon\办公设计\ABBYY_FineReader.ico", @ScriptDir &'\dhxtool' & "\icon\办公设计\ABBYY_FineReader.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\在线安装")
FileInstall("E:\ToolBox\软件工具箱\config\icon\在线安装\LKY_OfficeTools.ico", @ScriptDir &'\dhxtool' & "\icon\在线安装\LKY_OfficeTools.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\icon\常用网站")
FileInstall("E:\ToolBox\软件工具箱\config\icon\常用网站\Chrome.ico", @ScriptDir &'\dhxtool' & "\icon\常用网站\Chrome.ico", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\skin")
FileInstall("E:\ToolBox\软件工具箱\config\skin\water.dll", @ScriptDir &'\dhxtool' & "\skin\water.dll", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\主窗口背景.jpg", @ScriptDir &'\dhxtool' & "\skin\主窗口背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\提示背景.jpg", @ScriptDir &'\dhxtool' & "\skin\提示背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\欢迎背景.jpg", @ScriptDir &'\dhxtool' & "\skin\欢迎背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\水纹.bmp", @ScriptDir &'\dhxtool' & "\skin\水纹.bmp", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\软件大窗口背景.jpg", @ScriptDir &'\dhxtool' & "\skin\软件大窗口背景.jpg", 0)
FileInstall("E:\ToolBox\软件工具箱\config\skin\软件窗口背景.jpg", @ScriptDir &'\dhxtool' & "\skin\软件窗口背景.jpg", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\tools")
FileInstall("E:\ToolBox\软件工具箱\config\tools\7z.dll", @ScriptDir &'\dhxtool' & "\tools\7z.dll", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\7z.exe", @ScriptDir &'\dhxtool' & "\tools\7z.exe", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\aria2c.exe", @ScriptDir &'\dhxtool' & "\tools\aria2c.exe", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\Canon.ani", @ScriptDir &'\dhxtool' & "\tools\Canon.ani", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\ChkMbrPbr_x64.exe", @ScriptDir &'\dhxtool' & "\tools\ChkMbrPbr_x64.exe", 0)
FileInstall("E:\ToolBox\软件工具箱\config\tools\ChkMbrPbr_x86.exe", @ScriptDir &'\dhxtool' & "\tools\ChkMbrPbr_x86.exe", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\curl-ca-bundle.crt", @ScriptDir &'\dhxtool' & "\tools\curl\curl-ca-bundle.crt", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\curl.exe", @ScriptDir &'\dhxtool' & "\tools\curl\curl.exe", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\libcurl.def", @ScriptDir &'\dhxtool' & "\tools\curl\libcurl.def", 0)
DirCreate( @ScriptDir &'\dhxtool' & "\tools\curl")
FileInstall("E:\ToolBox\软件工具箱\config\tools\curl\libcurl.dll", @ScriptDir &'\dhxtool' & "\tools\curl\libcurl.dll", 0)
